### ISSUE TITLE
Error when changing the default style

### ISSUE THREAD

**Issue by jashshah** [mircealex/Movie_ratings_2016_17#1]
Hi, I am getting an error `OSError: 'seaborn' not found in the style library and input is not a valid URL or path. See style.available for list of available styles.` when I run your code. Although I solved this problem and managed to run the code by using a different style (`seaborn-white`), the graphs and the arrows are not properly aligned. Can you help me solve this problem?

**Comment by mircealex** [comment]
Hi @jashshah , I'm extremely sorry for the late reply, but I got absolutely no notification. In fact, I've discovered your issue by mistake. Nonetheless, please accept my apologies.

You get that error because `seaborn` is not within the list of pre-defined styles provided by the matplotlib library you have on your computer. You can see the styles available by running `plt.style.available`.

Try to update your matplotlib library. If you're using Linux, you can use `pip` and run `sudo pip install matplotlib --upgrade`.

Also, I have tried to change the style to `seaborn-white`, and the arrows are aligned as before, without changing any of their parameters.

If you're still interested in debugging this issue, let me know how it goes after upgrading matplotlib.

**Comment by jashshah** [comment]
Hi @mircealex thank you for taking the time to solve this issue, the solution works like a charm!

**Comment by mircealex** [comment]
I'm glad it worked @jashshah!

Thanks for taking a look at the project, and I apologize once more for the late reply.
